### PR TITLE
Use version 1 in file_id for downloading, PEP8 fixes

### PR DESCRIPTION
**Pull request by saketkc**
Not all metagenomes will have a file_id set
to the earlier default of 050.2. Also the parameter key was always undefined
TODO: Improve example to list the available
versions

### CODE REVIEW

**Comment by saketkc** [comment]
Good to merge?

**Comment by teharrison** [comment]
Saket,

Its fine to merge.  I just want you to be aware that that script is
deprecated and not recommended for downloading data from our system.  There
is a newer script with better error handling and more functionality here:

https://github.com/MG-RAST/MG-RAST-Tools/blob/master/tools/bin/mg-download.py

- Travis Harrison

**Comment by saketkc** [comment]
Thanks, Trevis! I was unaware of the new version. Thanks again, for merging though.

**Comment by saketkc** [comment]
Sorry about that typo.

**Pull request merged**
